package com.ufo.galaxy.runtime

/**
 * **Canonical host-session snapshot / projection** for the Android attached runtime (PR-19).
 *
 * This class is the authoritative, field-stable export of the local attached runtime
 * session state that is intended as a stable input source for the main-repo authoritative
 * session registry.
 *
 * ## Motivation
 *
 * [AttachedRuntimeSession.toMetadataMap] is a general-purpose metadata map used for
 * AIP v3 wire payloads and diagnostic logging.  That map uses `attached_session_*`
 * prefixed keys and is designed for internal session management.
 *
 * [AttachedRuntimeHostSessionSnapshot] provides a **dedicated projection layer** with
 * clean, short, registry-oriented field names and a guaranteed set of fields that are
 * semantically stable across all lifecycle transitions (attach / detach / reconnect /
 * invalidate).  The main-repo registry can consume this snapshot directly without
 * deriving state from multiple scattered fields.
 *
 * ## Required fields
 *
 * The following fields are **always present** in [toProjectionMap] regardless of
 * session lifecycle state:
 *
 *  | Projection key                        | Source                                          |
 *  |---------------------------------------|-------------------------------------------------|
 *  | [KEY_SESSION_ID]                      | [AttachedRuntimeSession.sessionId]              |
 *  | [KEY_DEVICE_ID]                       | [AttachedRuntimeSession.deviceId]               |
 *  | [KEY_RUNTIME_SESSION_ID]              | RuntimeController-level connection-cycle UUID   |
 *  | [KEY_ATTACHMENT_STATE]                | [AttachedRuntimeSession.State.wireValue]        |
 *  | [KEY_IS_REUSE_VALID]                  | [AttachedRuntimeSession.isReuseValid]           |
 *  | [KEY_DELEGATED_EXECUTION_COUNT]       | [AttachedRuntimeSession.delegatedExecutionCount]|
 *  | [KEY_HOST_ROLE]                       | [RuntimeHostDescriptor.FormationRole.wireValue] |
 *  | [KEY_POSTURE]                         | [SourceRuntimePosture] derived from state       |
 *
 * [KEY_INVALIDATION_REASON] is **conditionally present**: it is included only when
 * the session's [AttachedRuntimeSession.detachCause] is
 * [AttachedRuntimeSession.DetachCause.INVALIDATION].  For all other detach causes
 * (explicit detach, disconnect, disable) and while the session is active, this key
 * is absent.
 *
 * ## Posture derivation
 *
 * The [posture] field is derived from [AttachedRuntimeSession.state]:
 *  - [AttachedRuntimeSession.State.ATTACHED]  → [SourceRuntimePosture.JOIN_RUNTIME]
 *  - [AttachedRuntimeSession.State.DETACHING] → [SourceRuntimePosture.CONTROL_ONLY]
 *  - [AttachedRuntimeSession.State.DETACHED]  → [SourceRuntimePosture.CONTROL_ONLY]
 *
 * ## Projection semantics across lifecycle transitions
 *
 * ```
 * attach   → attachment_state=attached,  is_reuse_valid=true,  posture=join_runtime,   invalidation_reason=absent
 * detach   → attachment_state=detached,  is_reuse_valid=false, posture=control_only,   invalidation_reason=absent
 * reconnect→ new snapshot with new runtime_session_id; fields reset to attach defaults
 * invalidate→ attachment_state=detached, is_reuse_valid=false, posture=control_only, invalidation_reason=invalidation
 * ```
 *
 * ## Obtaining an instance
 *
 * Use the [from] factory in [RuntimeController]:
 * ```kotlin
 * val snapshot = AttachedRuntimeHostSessionSnapshot.from(
 *     session         = attachedSession,
 *     runtimeSessionId = currentRuntimeSessionId,
 *     hostDescriptor  = hostDescriptor
 * )
 * ```
 *
 * @property sessionId               Stable UUID for the [AttachedRuntimeSession].  Matches
 *                                   [AttachedRuntimeSession.sessionId].
 * @property deviceId                Hardware device identifier.  Matches
 *                                   [AttachedRuntimeSession.deviceId].
 * @property runtimeSessionId        Per-connection-cycle UUID generated by [RuntimeController]
 *                                   when the session is opened.  Distinct from [sessionId];
 *                                   changes on every new attach (reconnect).
 * @property attachmentState         [AttachedRuntimeSession.State.wireValue] of the current
 *                                   session state ("attached", "detaching", or "detached").
 * @property isReuseValid            `true` iff [AttachedRuntimeSession.isReuseValid].
 * @property delegatedExecutionCount Number of delegated tasks accepted under this session.
 * @property invalidationReason      [AttachedRuntimeSession.DetachCause.INVALIDATION] wire
 *                                   value when the session was invalidated; `null` otherwise.
 * @property hostRole                [RuntimeHostDescriptor.FormationRole.wireValue] of the
 *                                   attached host; defaults to
 *                                   [RuntimeHostDescriptor.FormationRole.DEFAULT] wireValue
 *                                   when no host descriptor is available.
 * @property posture                 [SourceRuntimePosture] value derived from the session state.
 */
data class AttachedRuntimeHostSessionSnapshot(
    val sessionId: String,
    val deviceId: String,
    val runtimeSessionId: String,
    val attachmentState: String,
    val isReuseValid: Boolean,
    val delegatedExecutionCount: Int,
    val invalidationReason: String?,
    val hostRole: String,
    val posture: String
) {

    /**
     * Produces an immutable projection map with stable, registry-oriented field names.
     *
     * All nine required fields are always present.  [KEY_INVALIDATION_REASON] is included
     * only when [invalidationReason] is non-null (i.e. when the session was invalidated).
     *
     * @return An immutable [Map] suitable for direct ingestion by the main-repo
     *         authoritative session registry.
     */
    fun toProjectionMap(): Map<String, Any> = buildMap {
        put(KEY_SESSION_ID, sessionId)
        put(KEY_DEVICE_ID, deviceId)
        put(KEY_RUNTIME_SESSION_ID, runtimeSessionId)
        put(KEY_ATTACHMENT_STATE, attachmentState)
        put(KEY_IS_REUSE_VALID, isReuseValid)
        put(KEY_DELEGATED_EXECUTION_COUNT, delegatedExecutionCount)
        put(KEY_HOST_ROLE, hostRole)
        put(KEY_POSTURE, posture)
        invalidationReason?.let { put(KEY_INVALIDATION_REASON, it) }
    }

    // ── Factory / companion ───────────────────────────────────────────────────

    companion object {

        // ── Projection key constants ──────────────────────────────────────────

        /** Projection key for [AttachedRuntimeSession.sessionId]. */
        const val KEY_SESSION_ID = "session_id"

        /** Projection key for [AttachedRuntimeSession.deviceId]. */
        const val KEY_DEVICE_ID = "device_id"

        /**
         * Projection key for the per-connection-cycle runtime session UUID generated
         * by [RuntimeController].  Distinct from [KEY_SESSION_ID].
         */
        const val KEY_RUNTIME_SESSION_ID = "runtime_session_id"

        /** Projection key for [AttachedRuntimeSession.State.wireValue]. */
        const val KEY_ATTACHMENT_STATE = "attachment_state"

        /** Projection key for [AttachedRuntimeSession.isReuseValid]. */
        const val KEY_IS_REUSE_VALID = "is_reuse_valid"

        /** Projection key for [AttachedRuntimeSession.delegatedExecutionCount]. */
        const val KEY_DELEGATED_EXECUTION_COUNT = "delegated_execution_count"

        /**
         * Projection key for the invalidation reason.  Present only when the session
         * was closed due to [AttachedRuntimeSession.DetachCause.INVALIDATION]; absent
         * in all other cases.
         */
        const val KEY_INVALIDATION_REASON = "invalidation_reason"

        /** Projection key for [RuntimeHostDescriptor.FormationRole.wireValue]. */
        const val KEY_HOST_ROLE = "host_role"

        /** Projection key for the [SourceRuntimePosture] value derived from session state. */
        const val KEY_POSTURE = "posture"

        /**
         * Builds an [AttachedRuntimeHostSessionSnapshot] from an [AttachedRuntimeSession],
         * a caller-supplied [runtimeSessionId], and an optional [RuntimeHostDescriptor].
         *
         * @param session          The current [AttachedRuntimeSession] to project.
         * @param runtimeSessionId Per-connection-cycle UUID maintained by [RuntimeController].
         * @param hostDescriptor   Optional host descriptor; when `null` the [hostRole] falls
         *                         back to [RuntimeHostDescriptor.FormationRole.DEFAULT].
         * @return A fully populated [AttachedRuntimeHostSessionSnapshot].
         */
        fun from(
            session: AttachedRuntimeSession,
            runtimeSessionId: String,
            hostDescriptor: RuntimeHostDescriptor?
        ): AttachedRuntimeHostSessionSnapshot = AttachedRuntimeHostSessionSnapshot(
            sessionId = session.sessionId,
            deviceId = session.deviceId,
            runtimeSessionId = runtimeSessionId,
            attachmentState = session.state.wireValue,
            isReuseValid = session.isReuseValid,
            delegatedExecutionCount = session.delegatedExecutionCount,
            invalidationReason = session.detachCause
                ?.takeIf { it == AttachedRuntimeSession.DetachCause.INVALIDATION }
                ?.wireValue,
            hostRole = hostDescriptor?.formationRole?.wireValue
                ?: RuntimeHostDescriptor.FormationRole.DEFAULT.wireValue,
            posture = if (session.isAttached) SourceRuntimePosture.JOIN_RUNTIME
                      else SourceRuntimePosture.CONTROL_ONLY
        )
    }
}
