package com.ufo.galaxy.runtime

/**
 * **Canonical attached-runtime host-session snapshot / projection** (PR-19, post-#533
 * dual-repo runtime unification master plan — Canonical Attached Runtime Host-Session
 * Snapshot Projection, Android side).
 *
 * [AttachedRuntimeHostSessionSnapshot] is the authoritative Android-side export of the
 * local runtime session's key state.  It is designed to be a **semantically stable,
 * field-consistent, state-transition-unambiguous** input for the main-repo authoritative
 * session registry.
 *
 * ## Why a typed snapshot is needed
 *
 * Prior to PR-19, the host could obtain session state via
 * [RuntimeController.currentSessionSnapshot], which returns a raw [Map<String,Any>].
 * While that map is complete, it:
 *  - Does not carry [AttachedRuntimeSession.DetachCause.INVALIDATION]-specific metadata
 *    in a first-class field.
 *  - Does not include the per-connection [runtimeSessionId], which enables session
 *    alignment across reconnect / replace / invalidate transitions.
 *  - Does not carry host identity ([hostRole], [posture]) inline, forcing the registry
 *    to join two separate data sources.
 *
 * [AttachedRuntimeHostSessionSnapshot] closes all three gaps in a single, typed,
 * immutable value object.
 *
 * ## Field semantics
 *
 * | Field                     | Source                                                | Behaviour                                        |
 * |---------------------------|-------------------------------------------------------|--------------------------------------------------|
 * | [sessionId]               | [AttachedRuntimeSession.sessionId]                    | Stable per-attachment UUID.                      |
 * | [deviceId]                | [AttachedRuntimeSession.deviceId]                     | Hardware device identifier.                      |
 * | [runtimeSessionId]        | [RuntimeController._currentRuntimeSessionId]          | Per-connection UUID; resets on each reconnect.   |
 * | [attachmentState]         | [AttachedRuntimeSession.state]                        | Lifecycle state.                                 |
 * | [isReuseValid]            | [AttachedRuntimeSession.isReuseValid]                 | Host-safe reuse flag.                            |
 * | [delegatedExecutionCount] | [AttachedRuntimeSession.delegatedExecutionCount]      | Task-acceptance counter for the current session. |
 * | [invalidationReason]      | [AttachedRuntimeSession.detachCause] == INVALIDATION  | Non-null only after explicit invalidation.       |
 * | [hostRole]                | [RuntimeHostDescriptor.formationRole]                 | Structural formation role.                       |
 * | [posture]                 | [RuntimeHostDescriptor.participationState]            | Runtime participation state.                     |
 *
 * ## Projection semantics across lifecycle events
 *
 * - **attach**: [attachmentState]=ATTACHED, [isReuseValid]=true, [invalidationReason]=null.
 * - **detach** (any non-invalidation cause): [attachmentState]=DETACHED or DETACHING,
 *   [isReuseValid]=false, [invalidationReason]=null.
 * - **reconnect**: [runtimeSessionId] changes; [sessionId] changes (new [AttachedRuntimeSession]);
 *   [attachmentState]=ATTACHED, [isReuseValid]=true, [invalidationReason]=null.
 * - **invalidate**: [attachmentState]=DETACHED, [isReuseValid]=false,
 *   [invalidationReason]=[AttachedRuntimeSession.DetachCause.INVALIDATION.wireValue].
 *
 * ## Obtaining an instance
 * Use the [from] factory:
 * ```kotlin
 * val snapshot = AttachedRuntimeHostSessionSnapshot.from(
 *     session          = runtimeController.attachedSession.value ?: return,
 *     runtimeSessionId = currentRuntimeSessionId,
 *     hostDescriptor   = hostDescriptor
 * )
 * ```
 *
 * Or use [RuntimeController.currentHostSessionSnapshot] which handles all null-safety
 * checks.
 *
 * @property sessionId               Stable UUID for this attachment session (per [AttachedRuntimeSession]).
 * @property deviceId                Hardware device identifier.
 * @property runtimeSessionId        Per-connection UUID generated by [RuntimeController]; resets
 *                                   on every WebSocket reconnect so the registry can detect
 *                                   reconnect events without inspecting raw connection state.
 * @property attachmentState         Current [AttachedRuntimeSession.State] of the session.
 * @property isReuseValid            `true` iff the session may accept new delegated tasks;
 *                                   mirrors [AttachedRuntimeSession.isReuseValid].
 * @property delegatedExecutionCount Number of delegated tasks accepted under this session.
 * @property invalidationReason      Non-null only when [attachmentState] is [AttachedRuntimeSession.State.DETACHED]
 *                                   and the cause is [AttachedRuntimeSession.DetachCause.INVALIDATION].
 *                                   Contains the [AttachedRuntimeSession.DetachCause.wireValue] of the
 *                                   invalidation cause.  Null for all other detach causes and while
 *                                   the session is active.
 * @property hostRole                [RuntimeHostDescriptor.FormationRole] of this Android host.
 * @property posture                 [RuntimeHostDescriptor.HostParticipationState] of this Android host.
 */
data class AttachedRuntimeHostSessionSnapshot(
    val sessionId: String,
    val deviceId: String,
    val runtimeSessionId: String,
    val attachmentState: AttachedRuntimeSession.State,
    val isReuseValid: Boolean,
    val delegatedExecutionCount: Int,
    val invalidationReason: String?,
    val hostRole: RuntimeHostDescriptor.FormationRole,
    val posture: RuntimeHostDescriptor.HostParticipationState
) {

    /**
     * Builds the canonical wire representation of this snapshot.
     *
     * Keys always present:
     *  - [KEY_SESSION_ID]
     *  - [KEY_DEVICE_ID]
     *  - [KEY_RUNTIME_SESSION_ID]
     *  - [KEY_ATTACHMENT_STATE]
     *  - [KEY_IS_REUSE_VALID]
     *  - [KEY_DELEGATED_EXECUTION_COUNT]
     *  - [KEY_HOST_ROLE]
     *  - [KEY_POSTURE]
     *
     * Keys conditionally present:
     *  - [KEY_INVALIDATION_REASON] — only when [invalidationReason] is non-null.
     *
     * @return An immutable [Map] suitable for merging into AIP v3 metadata payloads or
     *         serialising to the main-repo authoritative session registry.
     */
    fun toMetadataMap(): Map<String, Any> = buildMap {
        put(KEY_SESSION_ID, sessionId)
        put(KEY_DEVICE_ID, deviceId)
        put(KEY_RUNTIME_SESSION_ID, runtimeSessionId)
        put(KEY_ATTACHMENT_STATE, attachmentState.wireValue)
        put(KEY_IS_REUSE_VALID, isReuseValid)
        put(KEY_DELEGATED_EXECUTION_COUNT, delegatedExecutionCount)
        put(KEY_HOST_ROLE, hostRole.wireValue)
        put(KEY_POSTURE, posture.wireValue)
        invalidationReason?.let { put(KEY_INVALIDATION_REASON, it) }
    }

    // ── Factory / companion ───────────────────────────────────────────────────

    companion object {

        // ── Metadata key constants ────────────────────────────────────────────

        /** Metadata key for [sessionId]. */
        const val KEY_SESSION_ID = "host_session_snapshot_session_id"

        /** Metadata key for [deviceId]. */
        const val KEY_DEVICE_ID = "host_session_snapshot_device_id"

        /** Metadata key for [runtimeSessionId]. */
        const val KEY_RUNTIME_SESSION_ID = "host_session_snapshot_runtime_session_id"

        /** Metadata key for the [AttachedRuntimeSession.State.wireValue] of [attachmentState]. */
        const val KEY_ATTACHMENT_STATE = "host_session_snapshot_attachment_state"

        /** Metadata key for [isReuseValid]. */
        const val KEY_IS_REUSE_VALID = "host_session_snapshot_is_reuse_valid"

        /** Metadata key for [delegatedExecutionCount]. */
        const val KEY_DELEGATED_EXECUTION_COUNT = "host_session_snapshot_delegated_execution_count"

        /**
         * Metadata key for [invalidationReason].
         *
         * This key is **absent** from [toMetadataMap] output when [invalidationReason]
         * is `null` (i.e. the session is not detached due to INVALIDATION).
         */
        const val KEY_INVALIDATION_REASON = "host_session_snapshot_invalidation_reason"

        /** Metadata key for the [RuntimeHostDescriptor.FormationRole.wireValue] of [hostRole]. */
        const val KEY_HOST_ROLE = "host_session_snapshot_host_role"

        /** Metadata key for the [RuntimeHostDescriptor.HostParticipationState.wireValue] of [posture]. */
        const val KEY_POSTURE = "host_session_snapshot_posture"

        /**
         * Derives an [invalidationReason] value from the session's [AttachedRuntimeSession.detachCause].
         *
         * Returns the [AttachedRuntimeSession.DetachCause.wireValue] only when [detachCause]
         * is [AttachedRuntimeSession.DetachCause.INVALIDATION]; `null` for all other causes or
         * when [detachCause] is `null`.
         */
        private fun invalidationReasonFor(detachCause: AttachedRuntimeSession.DetachCause?): String? =
            if (detachCause == AttachedRuntimeSession.DetachCause.INVALIDATION) {
                detachCause.wireValue
            } else {
                null
            }

        /**
         * Creates an [AttachedRuntimeHostSessionSnapshot] from the authoritative runtime sources.
         *
         * @param session          The current [AttachedRuntimeSession].
         * @param runtimeSessionId Per-connection UUID from [RuntimeController].
         * @param hostDescriptor   Optional [RuntimeHostDescriptor]; when `null` the [hostRole]
         *                         defaults to [RuntimeHostDescriptor.FormationRole.DEFAULT] and
         *                         [posture] defaults to [RuntimeHostDescriptor.HostParticipationState.DEFAULT].
         */
        fun from(
            session: AttachedRuntimeSession,
            runtimeSessionId: String,
            hostDescriptor: RuntimeHostDescriptor?
        ): AttachedRuntimeHostSessionSnapshot = AttachedRuntimeHostSessionSnapshot(
            sessionId = session.sessionId,
            deviceId = session.deviceId,
            runtimeSessionId = runtimeSessionId,
            attachmentState = session.state,
            isReuseValid = session.isReuseValid,
            delegatedExecutionCount = session.delegatedExecutionCount,
            invalidationReason = invalidationReasonFor(session.detachCause),
            hostRole = hostDescriptor?.formationRole ?: RuntimeHostDescriptor.FormationRole.DEFAULT,
            posture = hostDescriptor?.participationState ?: RuntimeHostDescriptor.HostParticipationState.DEFAULT
        )
    }
}
